import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp } from 'lucide-react';

const FAQS = [
  {
    id: 1,
    q: 'How does AI-powered virtual try-on work for fashion brands?',
    a: "The process of AI virtual try-on involves computer vision and 3D draping algorithms to get a virtual garment onto users' photos or real-time camera feeds realistically. Upon photo upload or by clicking a camera button, the AI recognizes your body shape, posture and proportions. It then simply drapes the chosen garment over the model's body, taking into consideration the draping effect of cloth, shoulder design, and the figure it will be on. The outcome is a view closer to what the garment would look like once the model tried it on. For fashion brands, this technology helps to lower return rate, improve customers' confidence in their buying, and make the online shopping experience seem more personal and trustworthy.",
  },
  {
    id: 2,
    q: 'Do I Need a Traditional Photoshoot to Use Vizzle?',
    a: 'No, not at all. Vizzle is designed for just such a purpose. Traditional photoshoots involve studio booking, professional fashion models, styling, shooting individual styles and waiting for post-production editing, which can take from 1 to 2 weeks and cost up to ten thousand rupees per photoshoot. AI Vizzle automatically processes your garment photos even plain flat-lays or hanger images work, chooses the model and background suitable to your product from the platform and creates your professional model on catalogue images in minutes. This can be completed as may be done for 10 products or 10,000 products, the same speed and quality. This eliminates one of the most significant delays in pushing a new collection to market for clothing manufacturers, wholesalers and quickly changing fashion brands.',
  },
  {
    id: 3,
    q: 'Does Vizzle work well with all types of Indian clothing?',
    a: "Yes. What makes Vizzle different from most global AI photography products, all of which are designed for western wear, is its ability to particularly cater to the Indian fashion categories. With regards to traditional clothing like sarees and lehengas, salwar kameez, ethnic co-ord sets, sherwanis, kurtas and other traditional dresses, the platform functions correctly not only in terms of the draping styles but also for the fabric behaviours, embellishments etc. It is also for western wear, sport wear, children's clothing and accessories. Since the AI has been trained to recognize the drape and fit pattern of Indian clothing on various body shapes, the results appear realistic and natural rather than as a mere digitized superimposition.",
  },
  {
    id: 4,
    q: 'Can Vizzle integrate with Shopify, Myntra, or other e-commerce platforms?',
    a: 'Yes. The integration of  Vizzle with Shopify, Wix and WordPress is made with a plugin or through API connection. It also allows you to include virtual try-on capability in your product pages, permitting consumers to try clothes without having to leave the site. Direct integration for marketplace sellers is not necessary — you just download the catalogue pictures generated by the AI and upload them to your Amazon, Flipkart or Myntra seller account normally. We can provide help to your technical team for custom-built websites with a tailored API integration.',
  },
  {
    id: 5,
    q: 'Does the AI preserve fabric texture, prints, and embroidery in the final output?',
    a: "Yes, and this is one of the most crucial quality aspects of  Vizzle. It is trained uniquely on fashion pieces and thus the platform knows how to maintain the visual elements which make each piece distinct, such as the weave of fabric, print and block prints, embroidery work, zari work, sequins, and accuracy of colours etc. Most AI tools suffer from such inaccuracies or stylistic errors on elaborate ethnic clothing. You can rest assured that the quality of the garment will be retained with AI Vizzle's outputs so that the customer can see exactly what they are getting and that the skills of your brand are accurately depicted in every picture.",
  },
];

function FAQItem({ item, index, isOpen, onToggle }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 14 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.35, delay: index * 0.05 }}
      className={`bg-white rounded-2xl border ${isOpen ? 'border-slate-300 shadow-sm' : 'border-slate-200/90 shadow-xs'
        } hover:border-slate-300 transition-all overflow-hidden`}
    >
      <button
        type="button"
        onClick={() => onToggle(index)}
        aria-expanded={isOpen}
        className="w-full px-6 py-5 flex items-center justify-between text-left cursor-pointer select-none gap-4"
      >
        <span className="text-sm sm:text-base font-semibold text-slate-900 tracking-tight flex-1">
          {item.q}
        </span>

        <div
          className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-colors duration-200 ${isOpen ? 'bg-rose-50 text-rose-500' : 'bg-slate-50 text-slate-500'
            }`}
        >
          {isOpen ? (
            <ChevronUp size={16} strokeWidth={2.5} />
          ) : (
            <ChevronDown size={16} strokeWidth={2.5} />
          )}
        </div>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            key="answer"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-6 pt-1 text-sm sm:text-[14.5px] leading-relaxed text-slate-600 border-t border-slate-100/80 mt-1 pt-4">
              {item.a}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function BlogFAQSection() {
  const [openIndex, setOpenIndex] = useState(null);

  const handleToggle = (index) => {
    setOpenIndex((prev) => (prev === index ? null : index));
  };

  return (
    <section className="w-full py-16 sm:py-20 px-4">
      {/* ── Header Section ── */}
      <div className="max-w-3xl mx-auto text-center mb-12">
        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-slate-900 text-center tracking-tight">
          Quick Answers for New Readers
        </h2>
        <p className="text-slate-500 text-center text-xs sm:text-sm mt-3 mb-12 max-w-xl mx-auto leading-relaxed">
          First time here? These are the questions most people ask before they start with Vizzle.
        </p>
      </div>

      {/* ── Accordion List ── */}
      <div className="max-w-4xl mx-auto px-4 w-full space-y-4 mb-20">
        {FAQS.map((faq, index) => (
          <FAQItem
            key={faq.id}
            item={faq}
            index={index}
            isOpen={openIndex === index}
            onToggle={handleToggle}
          />
        ))}
      </div>
    </section>
  );
}
